server:
  port: 8072
spring:
  application:
    name: "cards"
  datasource:
    url: jdbc:mysql://localhost:3306/eazybytes
    username: tushar
    password: 19ft.1630@MYS
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active:
      - "qa"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#below management property will show all the endpoints of the Actuator functionality
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "cards"
    description: "Eazy Bank cards application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        cards: DEBUG
